---
title: "R Notebook"
output: html_notebook
---

```{r}
# Import needed libraries
library(readr)
library(lubridate)
library(ggplot2)
library(dplyr)
library(RCurl)
library(forcats)
library(broom)
library(rvest)
library(Metrics)

# Import turnover data
turnover_data <- read_csv("https://raw.githubusercontent.com/opencampus-sh/einfuehrung-in-data-science-und-ml/main/umsatzdaten_gekuerzt.csv", show_col_types = FALSE)

#import Kieler Woche data
kiwo <- read_csv("https://raw.githubusercontent.com/opencampus-sh/einfuehrung-in-data-science-und-ml/main/kiwo.csv", show_col_types = FALSE)

#import weather data
weather <- read_csv("https://raw.githubusercontent.com/opencampus-sh/einfuehrung-in-data-science-und-ml/main/wetter.csv", show_col_types = FALSE)

#import extended weather Data from "Deutscher Wetterdienst"
weatherDWD <- read_delim("https://raw.githubusercontent.com/g3r1t/Umsatzdaten_Dump/main/Klimadaten-DWD-20130701-20191231.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE, show_col_types = FALSE)

#import monthly overnight stay and arrival data for Kiel
tourism <- read_csv("https://raw.githubusercontent.com/g3r1t/Umsatzdaten_Dump/main/Ankuenfte%20und%20Uebernachtungen.csv", show_col_types = FALSE)

#import holidays
Feiertage <- read_csv("https://raw.githubusercontent.com/g3r1t/Umsatzdaten_Dump/main/Feiertage.csv", 
                      show_col_types = FALSE)

#import school holidays
Ferien <- read_csv("https://raw.githubusercontent.com/g3r1t/Umsatzdaten_Dump/main/Ferien.csv", 
                    show_col_types = FALSE)

#delete all deviating "Umsatz" from dataset
Rausschmeißer <- data.frame(matrix(ncol = 3, nrow = 0))
colnames(Rausschmeißer) <- c("Datum", "Warengruppe", "Umsatz")

for (e in unique(turnover_data$Warengruppe)) {
mean <- mean(subset(turnover_data, Warengruppe == e)$Umsatz)
sd <- sd(subset(turnover_data, Warengruppe == e)$Umsatz)
turnover <- subset(turnover_data, Warengruppe == e)
turnover <- subset(turnover, Umsatz < mean + 2*sd & Umsatz > mean - 2*sd)
Rausschmeißer <- rbind(Rausschmeißer, turnover) }
turnover_data <- Rausschmeißer


#full join to keep all data points from turnoverdata and kiwo
full_Dataset <- full_join(turnover_data, kiwo, by = "Datum")

#full join to to keep all observations
full_Dataset <- full_join(full_Dataset, weather, by = "Datum")

#change "Datum"-column of weatherDWD to date-format
weatherDWD$Datum <- as.Date(weatherDWD$Datum, "%d.%m.%Y")

#fulljoin weather DWD and full_Dataset
full_Dataset <- full_join(full_Dataset, weatherDWD, by="Datum")

#replace NAs from weather with data from DWD
full_Dataset$Temperatur.x[is.na(full_Dataset$Temperatur.x)] <- full_Dataset$Temperatur.y[is.na(full_Dataset$Temperatur.x)]

full_Dataset$Windgeschwindigkeit.x[is.na(full_Dataset$Windgeschwindigkeit.x)] <- full_Dataset$Windgeschwindigkeit.y[is.na(full_Dataset$Windgeschwindigkeit.x)]

full_Dataset$Bewoelkung[is.na(full_Dataset$Bewoelkung)] <- full_Dataset$Bedeckungsgrad[is.na(full_Dataset$Bewoelkung)]

full_Dataset$Bewoelkung <- round(full_Dataset$Bewoelkung)

#Create Column Monatscode to full_join tourism data with full_Dataset
for (e in as.numeric(row.names(full_Dataset))) {
  full_Dataset$Monatscode[e] <- paste(
  (year(full_Dataset$Datum[e])-2000),
  formatC(month(full_Dataset$Datum[e]), width = 2, format = "d", flag = "0"), sep = "")
  }
full_Dataset$Monatscode <- as.numeric(full_Dataset$Monatscode)
full_Dataset <- full_join(full_Dataset, tourism, by="Monatscode")

#join holidays/Feiertage with dataset
full_Dataset <- full_join(full_Dataset, Feiertage, by = "Datum")
full_Dataset[c(26:41)][is.na(full_Dataset[c(26:41)])] <- 0 #set all NAs to zero for boolean variable

#join school holidays/Ferien with dataset
full_Dataset <- full_join(full_Dataset, Ferien, by = "Datum", suffix = c(".Feiertage", ".Ferien"))
full_Dataset[c(42:57)][is.na(full_Dataset[c(42:57)])] <- 0 #set all NAs to zero for boolean variable

#replaces all NAs of days where there is no KiWo with 0 and makes it a categorical boolean variable
full_Dataset$KielerWoche[is.na(full_Dataset$KielerWoche)] <- 0
```


```{r}
#import and join weather codes
webpage <- read_html(paste("http://www.seewetter-kiel.de/seewetter/daten_symbole.htm")) #read html page
weather_codes <- html_table(webpage, trim = TRUE)#turn all html-tables into a list of table-DFs
weather_codes <- weather_codes[[1]]# select first element of list of DFs

weather_codes <- weather_codes[-1]#drop first column

colnames(weather_codes)[1] <- "Wettercode"#rename first column to for full_join with full_Dataset

full_Dataset <- full_join(full_Dataset, weather_codes, by = "Wettercode")

#Group Weathercodes
#https://wetterkanal.kachelmannwetter.com/was-ist-der-ww-code-in-der-meteorologie/  
full_Dataset$Wettergruppe[full_Dataset$Wettercode <= 3] <- "Bewölkung"
full_Dataset$Wettergruppe[full_Dataset$Wettercode >= 4 & full_Dataset$Wettercode <= 9] <- "Dunst, Rauch, Staub oder Sand"
full_Dataset$Wettergruppe[full_Dataset$Wettercode >= 10 & full_Dataset$Wettercode <= 19] <- "Trockenereignisse"
full_Dataset$Wettergruppe[full_Dataset$Wettercode >= 20 & full_Dataset$Wettercode <= 29] <- "Ereignisse der letzten Stunde, aber nicht zur Beobachtungszeit"
full_Dataset$Wettergruppe[full_Dataset$Wettercode >= 30 & full_Dataset$Wettercode <= 39] <- "Staubsturm, Sandsturm, Schneefegen oder -treiben"
full_Dataset$Wettergruppe[full_Dataset$Wettercode >= 40 & full_Dataset$Wettercode <= 49] <- "Nebel oder Eisnebel"
full_Dataset$Wettergruppe[full_Dataset$Wettercode >= 50 & full_Dataset$Wettercode <= 59] <- "Sprühregen"
full_Dataset$Wettergruppe[full_Dataset$Wettercode >= 60 & full_Dataset$Wettercode <= 69] <- "Regen"
full_Dataset$Wettergruppe[full_Dataset$Wettercode >= 70 & full_Dataset$Wettercode <= 79] <- "Schnee"
full_Dataset$Wettergruppe[full_Dataset$Wettercode >= 80 & full_Dataset$Wettercode <= 89] <- "Schauer"
full_Dataset$Wettergruppe[full_Dataset$Wettercode >= 90 & full_Dataset$Wettercode <= 99] <- "Gewitter"
full_Dataset$Wettergruppe[is.na(full_Dataset$Wettercode)] <- "Nischt"

full_Dataset <- subset(full_Dataset, Bewoelkung != -999) # drop nonsensical data


#Convert Dates to weekdays
full_Dataset$Wochentag <- weekdays(full_Dataset$Datum)


#Add Warengruppe for the "to be predicted"-dates since its missing in turnover-data
a <- as.data.frame(c(1:5)) #create data frame containing each "Warengruppe"-number
b <- seq(as.Date("2019/06/09"), as.Date("2019/07/30"), by="day") #create data frame of "to-be-predicted" time period
c <- merge(a,b)
colnames(c) <- c("Warengruppe", "Datum")
c <- left_join(c, full_Dataset, by="Datum")
c$Warengruppe.y <- c$Warengruppe.x
c <- c[-1]
colnames(c)[2] <- "Warengruppe"
full_Dataset <- rbind(full_Dataset, c)

#Add holiday-densitiy
full_Dataset$Feriendichte <- rowSums(select(full_Dataset, "Baden-Wuerttemberg.Ferien":"Thueringen.Ferien"))



#Convert Warengruppe to Warenname
# Create vector of product names
Warenname <- c("Brot", "Brötchen", "Crossaint", "Konditorei", "Kuchen", "Saisonbrot")

#for each "Warengruppe"-number at position "[e]" a new row entry in column "Warenname" is created. This works bcs the index of the "Warengruppenname" in the vector corresponds with the number of "Warengruppe".
for (e in as.numeric(row.names(full_Dataset))) #enumerate Dataframe, since row.names returns a string
  full_Dataset$Warenname[e] <- Warenname[as.numeric(full_Dataset$Warengruppe[e])]


#Add month variable
full_Dataset$Monat <- month(full_Dataset$Datum, label = TRUE)


#Add calendar week variable
full_Dataset$KalenderWoche <- strftime(full_Dataset$Datum, format = "%V")


#Add Wochenende create boolean value for all days == Samstag | Sonntag and for all day != Samstag & Sonntag
full_Dataset$Wochenende[full_Dataset$Wochentag == "Samstag" | full_Dataset$Wochentag == "Sonntag"] <- 1
full_Dataset$Wochenende[full_Dataset$Wochentag != "Samstag" & full_Dataset$Wochentag != "Sonntag"] <- 0


#Add windchill Temp(https://de.wikipedia.org/wiki/Windchill)
full_Dataset$Windchill <- 13.12 + 0.6215 * full_Dataset$Temperatur.x + (0.3965 * full_Dataset$Temperatur.x - 11.37) * ((full_Dataset$Windgeschwindigkeit.x*3600)/1000)**0.16


###DATA ELIMINATION
#drop data before there is data for "Umsatz" and after the "to-be-predicted time period
full_Dataset <- filter(full_Dataset, Datum >= "2013-07-01")
full_Dataset <- filter(full_Dataset, Datum <= "2019-07-30")

full_Dataset <- subset(full_Dataset, Warengruppe != "NA")
full_Dataset <- subset(full_Dataset, Warengruppe != "6") #No Saisonbrot in the predicted period
full_Dataset <- subset(full_Dataset, !(Monat == "Dez" & mday(Datum) == 31)) #Silvester fliegt aber mal sowas von raus
full_Dataset <- subset(full_Dataset, !(Monat == "Dez" & mday(Datum) == 24)) #und Weihnachten erst recht.... Ostern?
  
###Drop useless columns
full_Dataset[ , c('Wettercode',
                'Windgeschwindigkeit.y',
                'Temperatur.y',
                'Monatscode',
                'Bedeckungsgrad', 
                'Dampfdruck',
                "Luftdruck",
                "Wettererscheinung oder -zustand",
                "Baden-Wuerttemberg.Feiertage",
                "Bayern.Feiertage",
                "Berlin.Feiertage",
                "Brandenburg.Feiertage",
                "Bremen.Feiertage",
                "Hamburg.Feiertage",
                "Hessen.Feiertage",
                "Mecklenburg-Vorpommern.Feiertage",
                "Niedersachsen.Feiertage",
                "Nordrhein-Westfalen.Feiertage",
                "Rheinland-Pfalz.Feiertage",
                "Saarland.Feiertage",
                "Sachsen.Feiertage",
                "Sachsen-Anhalt.Feiertage",
                "Thueringen.Feiertage"
                )] <- list(NULL)
colnames(full_Dataset)[6] <- "Temperatur" #Both have ugly suffixes from joining the 2 different weather datasets before
colnames(full_Dataset)[7] <- "Windgeschwindigkeit"


###SAVE TO CSV FOR EASIER AND FASTER DATA IMPORT IN PROJECT "UMSATZVORHERSAGE"
write.csv(full_Dataset, "full_Dataset.csv", row.names = FALSE)
```


```{r}
#Calculate linear model to judge variable quality
mod <- lm(formula = Umsatz ~ as.factor(Warengruppe) + as.factor(KielerWoche) + as.factor(Bewoelkung) +
                            Sonnenscheindauer + Uebernachtungen + Ankuenfte + Aufenthaltsdauer  + as.factor(Feriendichte)+
                            as.factor(Wochentag) + as.factor(Monat) + as.factor(KalenderWoche) + as.factor(Wochenende) + as.factor(Wettergruppe),
                            data = full_Dataset)

summary(mod)
```